version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install -g json
      - sudo apt update             # Install the latest system updates.
      - sudo apt install -y awscli
      - aws --version             
      - chmod +x ./build_scripts/create_configuration.sh
      - sh ./build_scripts/create_configuration.sh
      - npm install
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'